all:
	make -C orig all
	make -C orig-padded all
	make -C orig-scp all
	make -C dmk all

clean:
	make -C orig clean
	make -C orig-padded clean
	make -C orig-scp clean
	make -C dmk clean
	make -C ima clean
	make -C sdf clean
